In [ ]:
import numpy as np
"""
矩阵
向量
标量
数组

全0矩阵
全1矩阵
单位矩阵：是一个n*n的方形矩阵，其主对角线元素为1，其余元素为0。


矩阵加减乘运算
数组加减乘运算


"""


In [18]:
#numpy 数组
import numpy as np
a=np.array([1,2,3,4])
a

#[[[],[]],[[],[]],[[],[]]]
a1=np.array([[1,2,3],[5,6,7], [4,5,6]])
print(a1)
#print(a1[1][3])
a1.shape#输出数组矩阵形态，元组2*3

a2=np.array([[1,2,3,4,5,6],[3,4,5,6,7,8],[52,4,2,6,7,8],[32,6,7,1,2,4],[2,5,7,8,3,4]])
a2
a2.shape
a2.dtype#获取精度最高的数据类型



[[1 2 3]
 [5 6 7]
 [4 5 6]]


dtype('int32')

In [31]:
a3=np.arange(1,30,2)
a3

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [29]:
a3[3:8]
a3[::2]
a3[:8:2]
a3[3:10:3]

array([ 7, 13, 19])

In [30]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
b=np.zeros([4,5])
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.eye(8)#单位矩阵

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [34]:
np.zeros([4,5],dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [35]:
np.ones(3)

array([1., 1., 1.])

In [36]:
np.ones([5,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.diag([1,2,3,4],k=0)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [38]:
np.diag([1,2,3,4],k=1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [45]:
np.diag([1,2,3,4],k=2)

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [46]:
np.linspace(1,10,num=10,retstep=True)#等差数列

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)

In [ ]:
"""
1、创建大小为20，值为0的向量
2、创建大小为15，第六个值为2的向量
3、创建一个值从20-99的向量
4、将3的向量倒置
5、创建一个4*4的单位矩阵
6、创建
"""

In [49]:
t1=np.zeros(20)
t1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [74]:
t3=np.arange(20,100,1)
t4=t3.T
t3,t4

(array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
        71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
        88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
        71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
        88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]))

In [63]:
t5=np.eye(4)
t5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
t7=np.random.randn(1,18)
t7

array([[ 0.35572763, -1.04659136, -1.40992816, -1.67206217,  0.06643795,
         0.09013416,  1.56817474,  1.56506288, -1.95103755, -0.4064322 ,
        -0.192103  , -0.44309312,  0.21378973,  0.26177516,  0.16478428,
        -0.40994586, -0.01940142,  0.95253077]])

In [71]:
t6=np.ones([15,15])
t6[1:-1,1:-1]=0
t6

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [4]:
t9=np.diag(1+np.arange(10),k=-1)
t9

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0]])

In [2]:
import numpy as np
t8=np.arange(1,13,1)
t8[3:8]=-t8[3:8]
t8

t8=np.arange(1,30)

array([ 1,  2,  3, -4, -5, -6, -7, -8,  9, 10, 11, 12])

In [ ]:
t10=[]
for i in range(6):
    i=((0,0),(0,0,0))
    t10.append(i)
t10

In [27]:
np.zeros(6,[('p',[('x',int,1),('y',int,1)]),('c',[('r',int,1),('g',int,1),('b',int,1)])])

array([((0, 0), (0, 0, 0)), ((0, 0), (0, 0, 0)), ((0, 0), (0, 0, 0)),
       ((0, 0), (0, 0, 0)), ((0, 0), (0, 0, 0)), ((0, 0), (0, 0, 0))],
      dtype=[('p', [('x', '<i4'), ('y', '<i4')]), ('c', [('r', '<i4'), ('g', '<i4'), ('b', '<i4')])])

In [6]:
a5=np.array([[1,2,3],[4,5,6],[7,8,9]])
a5[2,2]
a5[0:2,1:3]
a5[:-1,1:]

array([[2, 3],
       [5, 6]])

In [30]:
#随机创建数组
np.random.randn(20)
np.random.randint(20)
np.random.randint(20,size=(2,3))
#变维
np.random.randint(20,size=30).reshape(5,6)
s=np.random.randint(20,size=24).reshape(2,3,4)
s.reshape(-1)
s.flatten()

array([17, 16,  6, 18,  7,  1,  3,  8,  6, 11, 10,  7,  2,  4, 14,  5,  2,
        1, 19, 15,  3, 11, 16,  9])

In [51]:
"""
数组与矩阵的运算
Numpy 两大类型：
    array （ndarrary的简写)类型：N维数组
    matrix类型：矩阵类型，维数确定，只能是二维
    
"""

a1=np.array([[1,2,3,4],[5,6,7,8]])
a2=np.array([[11,12,13,14],[51,61,71,81]])

m1=np.mat([[1,2,3,4],[5,6,7,8]])
m2=np.mat([[11,21,31,41],[51,61,71,81]])

a1+a2
m1+m2
a1-a2
m1-m2
a1*a2
np.dot(a1,a2.T)
m3=m1*m2.T
m3


matrix([[ 310,  710],
        [ 726, 1766]])

In [21]:
import numpy as np
np.random.random(10)
np.random.random((3,3))
np.random.normal()
np.random.normal(10,100)
np.random.seed(6)
# np.random.randint(4,8,size=(3,5))

In [27]:
from numpy import *
num=0
while(num<5):
    random.seed(4)
    print(random.random())
    num+=1

0.9670298390136767
0.9670298390136767
0.9670298390136767
0.9670298390136767
0.9670298390136767


In [28]:
from numpy import *
num=0
random.seed(5)
while(num<5):
    print(random.random())
    num+=1

0.22199317108973948
0.8707323061773764
0.20671915533942642
0.9186109079379216
0.48841118879482914


In [66]:
a=np.arange(4).reshape(2,2)
a
b=np.array([1,2])
b
# np.tile(b,(2,1))
c=np.vstack([b]*a.shape[0])+a
c

d=np.tile(b,(2,1))+a#沿X轴复制1倍（相当于没有复制），再沿Y轴复制2倍
d

e=np.linalg.inv(a)
e
# a.dot(e)
# e.dot(a)

f=np.arange(1,16).reshape(3,5)
f
n=np.linalg.pinv(f)

c

array([[1, 3],
       [3, 5]])

In [52]:
import numpy as np
a=[[1],[2],[3]]
b=[[1],[2],[3]]
c=[[1],[2],[3]]
d=[[1],[2],[3]]
print(np.vstack((a,b,c,d)))


[[1]
 [2]
 [3]
 [1]
 [2]
 [3]
 [1]
 [2]
 [3]
 [1]
 [2]
 [3]]


In [16]:
import numpy as np
a1=np.arange(20,100)[20:10:-2]
a1

array([40, 38, 36, 34, 32])