In [42]:
#Numpy常用方法
import numpy as np

a1=np.random.randint(10,size=(3,3))
a1
a1.min()
a1.max()
a1.argmin()#值最小的下标值
a1.argmax()#值最大的下标值
a1.mean()#平均值
a1.sort()#排序

max(a1[0])#行最大值
max(a1[:,0])#列


np.unique(a1)#去重

sum(a1)#求和
sum(a1[0])
sum(a1[:,0])

np.power(3,a1)#x1的x2次方
np.abs(a1)#计算各元素的绝对值
np.sin(a1)#计算数组各元素的普通型和双曲型三角函数



4.777777777777778

In [71]:
#numpy 数组转置:可以将m行n列转换为n行m列
"""
1：T属性
transpose函数

"""
#1、一维转置仍未一维
a1=np.arange(6)
a1.T
np.transpose(a1)

#2、多维
a2=np.arange(24).reshape((2,3,4))
a2.T
np.transpose(a2)

#3、指定转换规则--对于高维数组，进行轴编号进行转置
a3=np.arange(24).reshape((2,3,4))
print(a3)
a3.transpose((0,2,1))

a3.swapaxes(0,2)




[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [104]:
a3=np.arange(16).reshape(4,4)

np.sum(a3)
np.sum(a3,axis=0)#按列排序
np.sum(a3,axis=1)#按行排序

np.random.shuffle(a3)#随机打散
# np.sort(a3,axis=0)
# np.sort(a3,axis=1)

# np.argsort(a3)
# np.argsort(a3,axis=0)
# np.argsort(a3,axis=1)

np.partition(a3,2)
# print(a3)
# np.argpartition(a3,3,axis=0)
# np.argpartition(a3,3,axis=1)

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [ 8,  9, 10, 11]])

In [ ]:
np.range().16

In [4]:
#合并操作
import numpy as np
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

z=np.array([7,8,9])
np.concatenate([x,y,z])

x1=np.concatenate([[1,2,3],[11,21,31]])
np.concatenate([x1,x1])

z
z.reshape(1,-1)
# np.concatenate([x1,z.reshape(1,-1)])

#分割操作
x=np.arange(10)
a,b,c=np.split(x,[3,7])
a
b
c

a1,b1=np.split(x,[5])
a1,b1

y=np.arange(16).reshape(4,4)
c1,d1=np.split(y,[2])
c1,d1=np.split(y,[2],axis=1)
c1,d1

c1,d1=np.vsplit(y,[2])
c1,d1=np.hsplit(y,[2])
c1,d1

c1,d1=np.split(y,[-1])
c1,d1

#索引
a=np.arange(10)
a[3]
a[3:8]
a[3:9:2]

b=np.random.randint(20,size=10)
# print(b)
x=[3,5,7]
b[x]

c=np.array([[1,2],[4,5]])
b[c]

d=np.arange(16)
d1=d.reshape(4,4)
# print(d1)
r=np.array([0,1,2])
c=np.array([1,2,3])
d1[r,c]

d1[0,c]
d1[:2,c]

c1=[True,True,False,True]
d1[0:2,c1]



#numpy和array 比较
a=np.arange(16)
print(a)
a<6
a>5
a!=6
np.any(a==0)
np.any(a>8)
np.any(a<0)

# np.sum(a<5)
# np.all(a<5)
# np.sum(a%2==0)
# np.sum(a%2==0,axis=0)
# np.sum(a%2==0 | (a>12))

# a[a<5]

# b=np.arange(16).reshape(4,4)
# b[:,3]
# b[b[:,2]%3==0,:]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


False

In [5]:
"""
1、创建一个值从0-15的4*4矩阵
t1=np.arange(16).reshape(4,4)
t1_mat=np.mat(t1)
t1_mat
2、从[23,0,5,0,0,78,0,9]找非0元素（np有一个函数，百度）
a = [0,2,3]
b = np.nonzero(a)
print(np.array(b).ndim)ndim数组维度
print(b)




3、创建3*4*5的随机数组,并找出最大值最小值

4、创建8*8棋盘格矩阵，利用tile

5、3*5矩阵与2*3矩阵相乘












"""







'\n1、创建一个值从0-15的4*4矩阵\nt1=np.arange(16).reshape(4,4)\nt1_mat=np.mat(t1)\nt1_mat\n2、从[23,0,5,0,0,78,0,9]找非0元素（np有一个函数，百度）\na = [0,2,3]\nb = np.nonzero(a)\nprint(np.array(b).ndim)ndim数组维度\nprint(b)\n\n\n\n\n3、创建3*4*5的随机数组,并找出最大值最小值\n\n4、创建8*8棋盘格矩阵，利用tile\n\n5、3*5矩阵与2*3矩阵相乘\n\n\n\n\n\n\n\n\n\n\n\n\n'

In [89]:
t6=np.random.randint(50,size=15)
t6.sort()
print(t6)
t6.mean()

[ 3  3  3  5  7  8 15 25 25 26 29 33 33 36 43]


19.6

In [97]:
t3=np.random.randint(30,size=60).reshape(3,4,5)
print(t3.min())
t3.max()


29

In [103]:
t1=np.arange(16).reshape(4,4)
t1_mat=np.mat(t1)
t1_mat

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [106]:
t9=np.random.randint(30,size=40).reshape(8,5)
print(t9.argmax())


33


In [111]:
t11=np.linspace(1,5,num=20)
t11//1
t11.astype(int)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 5])

In [2]:
import numpy as np
b8=np.arange(1,6).reshape(5,1)
b88=np.tile(b8,(1,5))
b8=np.mat(b88)
b8




matrix([[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5]])

In [3]:
b7=np.mat([1,2,3,4,5])
b7
np.tile(b7,(5,1))


matrix([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

In [4]:
b9=np.random.randint(40,size=(8,5))
print(b9)
num1=np.argmax(b9)//5
num2=np.argmax(b9)%5
b9[num1,num2]=5
b9

[[18 28 27 10 12]
 [29  4  5 37  3]
 [27  0 26  8 30]
 [20 26 30 17  7]
 [27  8 14 21 36]
 [14 17 25  2 15]
 [ 9 15 20 24 31]
 [25 33 38 12 37]]


array([[18, 28, 27, 10, 12],
       [29,  4,  5, 37,  3],
       [27,  0, 26,  8, 30],
       [20, 26, 30, 17,  7],
       [27,  8, 14, 21, 36],
       [14, 17, 25,  2, 15],
       [ 9, 15, 20, 24, 31],
       [25, 33,  5, 12, 37]])

In [5]:
x=np.mat((np.arange(1,21).reshape(20,1)))
print(x)
y=np.zeros([20,3])
print(y)
a=np.hstack((x,y)) 
print(a)
b=np.array(a).reshape(1,80)
print(b)
b[:,:-3]


[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 1.  0.  0.  0.]
 [ 2.  0.  0.  0.]
 [ 3.  0.  0.  0.]
 [ 4.  0.  0.  0.]
 [ 5.  0.  0.  0.]
 [ 6.  0.  0.  0.]
 [ 7.  0.  0.  0.]
 [ 8.  0.  0.  0.]
 [ 9.  0.  0.  0.]
 [10.  0.  0.  0.]
 [11.  0.  0.  0.]
 [12.  0.  0.  0.]
 [13.  0.  0.  0.]
 [14.  0.  0.  0.]
 [15.  0.  0.  0.]
 [16.  0.  0.  0.]
 [17.  0.  0.  0.]
 [18.  0.  0.  0.]
 [19.  0.  0.  0.]
 [20.  0.  0.  0.]]
[[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.  0.
   0.  0.  6.  0.  0.  0.  7.  0.  0.  0.  8.  0.  0.  0.  9.  0.  0.  0.
  10.  0.  0.  0. 11.  0.  0.  0. 12.  0.  0.  0. 13.  0.  0.  0. 14.  0.
   0.  0. 15.  0.  0.  0. 16.  0.  

array([[ 1.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  4.,
         0.,  0.,  0.,  5.,  0.,  0.,  0.,  6.,  0.,  0.,  0.,  7.,  0.,
         0.,  0.,  8.,  0.,  0.,  0.,  9.,  0.,  0.,  0., 10.,  0.,  0.,
         0., 11.,  0.,  0.,  0., 12.,  0.,  0.,  0., 13.,  0.,  0.,  0.,
        14.,  0.,  0.,  0., 15.,  0.,  0.,  0., 16.,  0.,  0.,  0., 17.,
         0.,  0.,  0., 18.,  0.,  0.,  0., 19.,  0.,  0.,  0., 20.]])

In [6]:
b=np.linspace(1,5,num=5,dtype=int)
b.transpose
c=np.eye(5)
c[:,0]=b
c


array([[1., 0., 0., 0., 0.],
       [2., 1., 0., 0., 0.],
       [3., 0., 1., 0., 0.],
       [4., 0., 0., 1., 0.],
       [5., 0., 0., 0., 1.]])

In [14]:
t9=np.random.randint(10,size=40).reshape(8,5)
print(t9)
for i in range(len(t9)):
    num1=(t9.argmax())//5
    num2=(t9.argmax())%5
    t9[num1,num2]=5
t9

[[2 3 4 1 7]
 [7 4 1 4 6]
 [6 2 1 6 0]
 [6 8 5 9 2]
 [5 0 0 7 4]
 [8 5 5 4 7]
 [1 7 0 1 6]
 [6 3 9 9 3]]


array([[2, 3, 4, 1, 5],
       [5, 4, 1, 4, 6],
       [6, 2, 1, 6, 0],
       [6, 5, 5, 5, 2],
       [5, 0, 0, 5, 4],
       [5, 5, 5, 4, 7],
       [1, 7, 0, 1, 6],
       [6, 3, 5, 5, 3]])

In [17]:
b11=np.linspace(1,5,num=20,retstep=False)
print(np.floor(b11))
print(np.ceil(b11)-1)
print(b11.astype(int))
print(np.trunc(b11))

[1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 3. 3. 3. 3. 3. 4. 4. 4. 4. 5.]
[0. 1. 1. 1. 1. 2. 2. 2. 2. 2. 3. 3. 3. 3. 3. 4. 4. 4. 4. 4.]
[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 5]
[1. 1. 1. 1. 1. 2. 2. 2. 2. 2. 3. 3. 3. 3. 3. 4. 4. 4. 4. 5.]


In [19]:
x1=np.random.randint(5,size=4)
print(x1)
x2=np.random.randint(9,size=4)
print(x2)
np.intersect1d(x1,x2)

[1 3 3 0]
[6 7 8 0]


array([0])

In [21]:
x = np.random.randint(1, 10, (3, 3))
print(x)
x[:,0].argsort()   
x = x[x[:, 0].argsort()]
print(x)

[[5 8 6]
 [5 2 7]
 [4 8 6]]
[[4 8 6]
 [5 8 6]
 [5 2 7]]


In [22]:
x = np.array([2,3,1,1,4])
count = np.bincount(x)
print(count)
common_value = np.argmax(count)
print(common_value)


[0 2 1 1 1]
1


In [48]:
a=np.random.randint(0,5,(10,10))
print(a)
n=3
# i=1+(a.shape[0]-3)
# j=1+(a.shape[1]-3)
b=np.lib.stride_tricks.as_strided(a,shape=(8,8,3,3),strides=a.strides+a.strides)
print(b)




[[3 3 1 1 0 0 2 3 4 3]
 [0 2 1 3 3 1 1 2 2 4]
 [2 1 4 4 3 0 3 2 0 4]
 [2 3 1 3 1 4 1 0 0 0]
 [1 2 0 0 2 2 2 3 3 0]
 [3 3 4 4 3 0 2 2 1 1]
 [0 4 1 4 2 0 0 0 0 3]
 [2 4 3 2 3 1 3 0 4 4]
 [1 3 2 4 4 0 4 4 2 1]
 [4 3 3 4 4 0 3 2 4 0]]
[[[[3 3 1]
   [0 2 1]
   [2 1 4]]

  [[3 1 1]
   [2 1 3]
   [1 4 4]]

  [[1 1 0]
   [1 3 3]
   [4 4 3]]

  [[1 0 0]
   [3 3 1]
   [4 3 0]]

  [[0 0 2]
   [3 1 1]
   [3 0 3]]

  [[0 2 3]
   [1 1 2]
   [0 3 2]]

  [[2 3 4]
   [1 2 2]
   [3 2 0]]

  [[3 4 3]
   [2 2 4]
   [2 0 4]]]


 [[[0 2 1]
   [2 1 4]
   [2 3 1]]

  [[2 1 3]
   [1 4 4]
   [3 1 3]]

  [[1 3 3]
   [4 4 3]
   [1 3 1]]

  [[3 3 1]
   [4 3 0]
   [3 1 4]]

  [[3 1 1]
   [3 0 3]
   [1 4 1]]

  [[1 1 2]
   [0 3 2]
   [4 1 0]]

  [[1 2 2]
   [3 2 0]
   [1 0 0]]

  [[2 2 4]
   [2 0 4]
   [0 0 0]]]


 [[[2 1 4]
   [2 3 1]
   [1 2 0]]

  [[1 4 4]
   [3 1 3]
   [2 0 0]]

  [[4 4 3]
   [1 3 1]
   [0 0 2]]

  [[4 3 0]
   [3 1 4]
   [0 2 2]]

  [[3 0 3]
   [1 4 1]
   [2 2 2]]

  [[0 3 2]
   [4 1 0]
   [2 2 